### ISSUE TITLE
ed25519 type issue

### ISSUE THREAD

**Issue by franziskuskiefer** [HACS-workshop/hacspec#23]
While adding python type checking ([see branch](https://github.com/HACS-workshop/hacspec/tree/new-arrays)) I noticed `recover_x_coordinate` returns `None`, which is not a valid `felem := nat := int`.
The `None` return case is only exercised in `vrf.py`.
@Frosne can you have a look?

**Comment by Frosne** [comment]
Hi, 

you mean you would rather have here (https://github.com/HACS-workshop/hacspec/blob/8d9642995cc2ee884fea402cb19f6ffcaa207940/specs/vrf.py#L85) None as the result or you prefer me to get rid of None's at all?

**Comment by franziskuskiefer** [comment]
Currently the return type of `recover_x_coordinate` is `felem`, which doesn't allow `None` but `false` isn't a `felem` either. So I guess we need a return type here that's not only `felem` but can have some kind of bottom value for failure cases. Either make the return type a `Union` or add a new type that can have a failure case.

**Comment by franziskuskiefer** [comment]
Fixed in PR #30
